---
apiVersion: "config.istio.io/v1alpha2"
kind: denier
metadata:
  name: handler
spec:
  status:
    code: 401
    message: Not Authorized
---
apiVersion: "config.istio.io/v1alpha2"
kind: checknothing
metadata:
  name: denyrequest
spec:
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: denycarspi
spec:
  match: destination.labels["app"]=="cars-api" && (request.headers["authorization"]|"unauthorized") == "unauthorized"
  actions:
  - handler: handler.denier
    instances: [ denyrequest.checknothing]