---
apiVersion: "config.istio.io/v1alpha2"
kind: denier
metadata:
  name: carsapi-handler
  namespace: istio-system
spec:
  status:
    code: 16
    message: You must be authenticated to access the service
---
apiVersion: "config.istio.io/v1alpha2"
kind: checknothing
metadata:
  name: carsapi-denyrequest
  namespace: istio-system
spec:
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: carspi-deny
  namespace: istio-system
spec:
  match: destination.service == "cars-api.myproject.svc.cluster.local" && request.headers["authorization"] == "unauthorized"
  actions:
  - handler: carsapi-handler.denier.istio-system
    instances: [carsapi-denyrequest.checknothing.istio-system]