---
kind: Service
apiVersion: v1
metadata:
  name:  cars-web
  labels:
    app: cars-web
    version: v1
spec:
  selector:
    app:  cars-web
  ports:
  - name:  http
    port:  80
    targetPort:  8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: cars-web
    version: v1
  name: cars-web
spec:
  replicas: 1
  selector:
    app: cars-web
  template:
    metadata:
      annotations: {}
      labels:
        app: cars-web
        version: v1
    spec:
      containers:
      - name: spring-boot
        image: docker.io/kameshsampath/cars-web:1.0
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 10